### ISSUE TITLE
Usage with NPM?

### ISSUE THREAD

**Issue by PrestonN** [horsepress/videoJsABLoopPlugin#5]
Hello!

I was interested in using your plugin with my project, however it doesn't look like it plays nicely with NPM / Node based projects.  I was wondering if you had any documentation on setting it up for this use case?  Any time I import it into my project it simply errors out.  If you need any additional information or a code example then please let me know.

Thanks!

**Comment by phhu** [comment]
Hello,

You're right, it could do with being modularised. 

The fork at https://github.com/pbellesa/videojs-abloop has this done simply for node.js / common js modules and might work

I'll try to get it changed to use JS modules as per the videojs project soon. 

Might be worth making it into an advanced plugin as per https://docs.videojs.com/tutorial-plugins.html (esp event handling)

**Comment by phhu** [comment]
...a code sample would be great if you could send one.

**Comment by PrestonN** [comment]
Thanks for sharing the fork.  The documentation that's over there (as far as setup and configuration) would likely be a better code example than what I could provide.  I wouldn't imagine the fork being worth using though considering how old it is.

If you still need a code example from me though, my plan is to include the functionality [here](https://github.com/FreeTubeApp/FreeTube-Vue/blob/master/src/renderer/components/ft-video-player/ft-video-player.js#L123) within my project.

The setup would likely be similar to their getting started documentation:

```javascript
import videojs from 'video.js'
import 'abLoopPlugin'

const player = videojs(elementId)

// Some plugins either auto-detect the videoJS instance or have the instance passed as a parameter
abLoopPlugin(videojs, { configOptions })
```

If you need anything else from me, then please let me know.

**Comment by phhu** [comment]
Thanks, I'll try to get this done soon

**Comment by phhu** [comment]
I've updated the code (v1.1.2)  in github / npm so that it works in node etc as an ES6 module.

Could you please try using this and let me know if it works ok?

Something like this:

```js
import videojs from 'video.js'    
import abLoopPlugin from 'videojs-abloop'      // use v1.1.2

abLoopPlugin(window,videojs);

const player = videojs('vid',{     //vid is the video element id
  plugins: {
    abLoopPlugin: {
      'start':3
    }
  }
});
player.abLoopPlugin.setEnd(6.5).playLoop();
````

**Comment by phhu** [comment]
I think this is fixed - please let me know if there are any issues.
